# Generated by Django 5.2 on 2026-08-28 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_course_options_alter_course_code_and_more"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ["course__code", "semester", "code"]},
        ),
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="subject",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subjects",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="semester",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("course", "code"), name="unique_subject_code_per_course"
            ),
        ),
    ]
