# Generated by Django 5.2 on 2026-08-25 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0002_teacher_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="department",
        ),
    ]
