# Generated by Django 5.2 on 2026-08-27 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0001_initial"),
        ("teachers", "0004_teacher_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teachers",
                to="departments.department",
            ),
        ),
    ]
