# Generated by Django 5.2 on 2026-08-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0002_alter_subject_options_alter_subject_code_and_more"),
        ("teachers", "0005_alter_teacher_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="teachers", to="subjects.subject"
            ),
        ),
    ]
