# Generated by Django 5.2 on 2026-08-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="course",
        ),
    ]
