# Generated by Django 5.2 on 2026-08-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_remove_subject_course"),
        ("results", "0003_alter_result_subject"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subject",
        ),
    ]
