# Generated by Django 5.2 on 2026-08-25 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_delete_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="department",
        ),
    ]
