# Generated by Django 5.2 on 2026-08-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="attendance",
            name="remarks",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("Present", "Present"),
                    ("Absent", "Absent"),
                    ("Late", "Late"),
                ],
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="subject",
        ),
    ]
