# Generated by Django 5.2 on 2026-08-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0002_alter_attendance_unique_together_attendance_remarks_and_more",
        ),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-date", "student"]},
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("student", "date"), name="unique_student_attendance_per_date"
            ),
        ),
    ]
